services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: brokers.rabbitmq
    hostname: brokers.rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
    security_opt:
      - no-new-privileges:true

  kafka:
    image: bitnami/kafka:3.5.0
    container_name: brokers.kafka
    hostname: brokers.kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "true"
    security_opt:
      - no-new-privileges:true

  nats:
    image: nats
    container_name: brokers.nats
    hostname: brokers.nats
    restart: unless-stopped
    command: -js
    ports:
      - "4222:4222"
      - "8222:8222"
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:alpine
    container_name: brokers.redis
    hostname: brokers.redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    security_opt:
      - no-new-privileges:true
