services:
  redis:
    image: redis:alpine
    container_name: brokers.redis
    hostname: brokers.redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    security_opt:
      - no-new-privileges:true
